[package]
name = "buttplug-rs-ffi"
version = "0.1.0"
authors = ["Kyle Machulis <kyle@nonpolynomial.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# buttplug = { path = "../../buttplug-rs/buttplug", features = ["async-std-runtime", "client", "server", "serialize-json", "btleplug-manager", "websockets", "xinput-manager", "serial-manager", "lovense-dongle-manager"] }
buttplug = { version = "0.11.0", features = ["async-std-runtime", "client", "server", "serialize-json", "btleplug-manager", "websockets", "xinput-manager", "serial-manager", "lovense-dongle-manager"] }
async-std = "1.6.3"
tracing-subscriber = "0.2.12"
futures = "0.3.5"
tracing = "0.1.19"
dashmap = "3.11.10"
libc = "0.2.77"
prost = "0.6.1"
async-channel = "1.5.1"
lazy_static = "1.4.0"

[build-dependencies]
prost-build = "0.6.1"
vergen = "3.1.0"

[lib]
name = "buttplug_ffi"
path = "src/lib.rs"
crate-type = ["cdylib"]

