[package]
name = "buttplug-rs-ffi"
version = "0.1.0"
description = "FFI Layer for buttplug-rs. Used by other languages for implementing buttplug-rs bindings."
authors = ["Kyle Machulis <kyle@nonpolynomial.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["buttplug/async-std-runtime", "buttplug/btleplug-manager", "buttplug/websockets", "buttplug/xinput-manager", "buttplug/serial-manager", "buttplug/lovense-dongle-manager"]
wasm = ["wasm-bindgen", "uuid", "web-sys", "js-sys", "tracing-wasm", "buttplug/wasm-bindgen-runtime", "async-trait", "wasm-bindgen-futures", "broadcaster"]

[dependencies]
buttplug = { version = "0.11.2", default-features = false, features = ["client", "server", "serialize-json"] }
# buttplug = { path = "../../buttplug-rs/buttplug", default-features = false, features = ["client", "server", "serialize-json"] }
async-std = "1.8.0"
tracing-subscriber = "0.2.15"
futures = "0.3.8"
tracing = "0.1.22"
dashmap = "3.11.10"
libc = "0.2.81"
prost = "0.6.1"
async-channel = "1.5.1"
lazy_static = "1.4.0"
wasm-bindgen = { version = "0.2.69", features = ["serde-serialize"], optional = true }
# Needed to build valico with wasm-bindgen
uuid = { version = "0.8.1", features = ["wasm-bindgen"], optional = true }
async-lock = "2.3.0"
js-sys = { version = "0.3.46", optional = true }
tracing-wasm = { version = "0.1.0", optional = true }
async-trait = { version = "0.1.42", optional = true }
wasm-bindgen-futures = { version = "0.4.19", optional = true }
broadcaster = { version = "1.0.0", optional = true }

[build-dependencies]
prost-build = "0.6.1"
vergen = "3.1.0"

[lib]
name = "buttplug_rs_ffi"
path = "src/lib.rs"
crate-type = ["cdylib"]

[build]
rustflags = ["--cfg=web_sys_unstable_apis"]

[dependencies.web-sys]
version = "0.3.46"
# path = "../../wasm-bindgen/crates/web-sys"
#git = "https://github.com/rustwasm/wasm-bindgen"
optional = true
features = [
  "Navigator",
  "Bluetooth",
  "BluetoothDevice",
  "BluetoothLeScanFilterInit",
  "BluetoothRemoteGattCharacteristic",
  "BluetoothRemoteGattServer",
  "BluetoothRemoteGattService",
  "BinaryType",
  "Blob",
  "console",
  # "DataView",
  "ErrorEvent",
  "Event",
  "FileReader",
  "MessageEvent",
  "ProgressEvent",
  "RequestDeviceOptions",
  "WebSocket",
  "Window"
]
