[package]
name = "buttplug-rs-ffi"
version = "0.1.0"
authors = ["Kyle Machulis <kyle@nonpolynomial.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# buttplug = { path = "../../buttplug-rs/buttplug", features = ["async-std-runtime", "client", "server", "serialize-json", "btleplug-manager", "websockets", "xinput-manager", "serial-manager", "lovense-dongle-manager"] }
buttplug = { version = "0.7.3", features = ["async-std-runtime", "client", "server", "serialize-json", "btleplug-manager", "websockets", "xinput-manager", "serial-manager", "lovense-dongle-manager"] }
async-std = "1.6.3"
flatbuffers = "0.6.1"
tracing-subscriber = "0.2.12"
futures = "0.3.5"
tracing = "0.1.19"
dashmap = "3.11.10"

[build-dependencies]
flatc-rust = "0.1.3"

[lib]
name = "buttplug_ffi"
path = "src/lib.rs"
crate-type = ["cdylib"]
